# Generated by Django 3.2.3 on 2021-05-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210516_2110'),
        ('main_app', '0003_userprofile'),
    ]

    operations = [
    ]
