# Generated by Django 3.2.3 on 2021-05-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_merge_0003_auto_20210516_2110_0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
